[book]
authors = ["Chris Walquist"]
language = "en"
multilingual = false
src = "src"
title = "House of Kwa"

[output.html]
default-theme = "rust"

[build]
build-dir = "../docs"
create-missing = false
